# Stage1: UI Build
FROM node:14-slim
WORKDIR /usr/src/ui
COPY ui/ .
# Create user
RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1001 racosta -p "Nada"
RUN npm install
EXPOSE 3000
CMD ["npm", "start"]

