# Pull the Node image from Docker Hub
FROM node:14-slim

# Setting Working Directory
WORKDIR /usr/app

# Copying only package.json
COPY package*.json ./

# Create user
RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1001 racosta -p "Nada"

# Install Dependencies
RUN npm install 

# Copy rest of the code to container
COPY . .

EXPOSE 3000

# Run the React app
CMD ["npm", "start"]



