name: GitOPS-DEV

on:
  push:
    branches:
      - 'Dev'
    paths:
      - 'Terraform/Dev/**'
jobs:
  Terraforming:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      
      - name: Verify Terraform version
        run: terraform --version
      
      - name: Terraform init
        run: terraform init --var-file="Terraform/Dev/dev.tfvars" -input=false
      
      - name: Terraform validation
        run: terraform validate
      
      - name: Terraform apply
        run: terraform apply --var-file="Terraform/Dev/dev.tfvars" -auto-approve -input=false
