name: GitOPS-Stage

on:
  push:
    branches:
      - 'Stage'
    paths:
      - 'Terraform/Stage/**'
jobs:
  Terraforming:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      
      - name: Verify Terraform version
        run: terraform --version
      
      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init --var-file="Terraform/Stage/stage.tfvars" -input=false
      
      - name: Terraform validation
        run: terraform validate
      
      - name: Terraform apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_db_user: ${{secrets.TF_VAR_DB_USER}}
          TF_VAR_db_pass: ${{secrets.TF_VAR_DB_PASS}}
        run: terraform apply --var-file="Terraform/Stage/stage.tfvars" -auto-approve -input=false
