name: cd-test

on:
  push:
    branches:
      - 'Dev'
    paths:
      - 'dev/**'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
